version: '3.8'

services:
  app:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=postgres://postgres:password@db:5432/portfolio

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
